### PR TITLE
Feature/694

### PR DESCRIPTION
**Pull request by jj105**
# Resolves [694](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/694)

### CODE REVIEW

**Review by devbtech — APPROVED** [review]

**Comment by devbtech** [comment]
@mtg137 Please resolve conflicts

**Comment by mtg137** [comment]
it's not my PR.

**Comment by jj105** [comment]
I'll resolve conflicts.

**Comment by jj105** [comment]
it's fixed now.

**Review by devbtech — APPROVED** [review]

**Pull request merged**
